In [1279]:
import pandas as pd
import numpy as np
import json

In [1280]:
with open('churn_nordeste_raw.json', 'r') as f:
    json_bruto = json.load(f)

In [1281]:
json_bruto

{'regional': 'Nordeste',
 'data_extracao': '2026-02-13',
 'clientes': [{'id_cliente': 'NE-10201',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 12,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '89,90',
    'cobranca_total': '1078,80'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10202',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 48,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '45,50',
    'cobranca_total': '2184,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10203',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 2,
    'tipo_contrato': 'Mensal',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '120,00',
    'cobranca_total': '240,00'},
   'servicos': {'telefone': 'Nao',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Sim',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10204',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 24,
    'tipo_contrato': 'Um ano',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '75,30',
    'cobranca_total': '1807,20'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10205',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 1,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '99,99',
    'cobranca_total': '99,99'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10206',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 36,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '55,00',
    'cobranca_total': '1980,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10207',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 8,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '110,50',
    'cobranca_total': '884,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10208',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 15,
    'tipo_contrato': 'Um ano',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '65,00',
    'cobranca_total': '975,00'},
   'servicos': {'telefone': 'Nao',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10209',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 450,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '70,00',
    'cobranca_total': '31500,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10210',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 18,
    'tipo_contrato': 'Um ano',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '0,01',
    'cobranca_total': '0,18'},
   'servicos': {'telefone': 'Nao',
    'internet': 'DSL',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10211',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 60,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '50,00',
    'cobranca_total': '3000,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10212',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 6,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '890,00',
    'cobranca_total': '5340,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10213',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Nao',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 30,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '85,00',
    'cobranca_total': '2550,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10214',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 10,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '95,00',
    'cobranca_total': '950,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10215',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 42,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '58,00',
    'cobranca_total': '2436,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'}]}

In [1282]:
dados_normalizados = pd.json_normalize(json_bruto, record_path='clientes', meta=['regional', 'data_extracao'], sep='_')

In [1283]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,"89,90","1078,80",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,"45,50","2184,00",Sim,DSL,Sim,Sim,Nordeste,2026-02-13
2,NE-10203,Sim,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,"120,00","240,00",Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
3,NE-10204,Nao,Feminino,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,"75,30","1807,20",Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,"99,99","99,99",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
5,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,"55,00","1980,00",Sim,DSL,Sim,Sim,Nordeste,2026-02-13
6,NE-10207,Nao,Masculino,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,"110,50","884,00",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10208,Nao,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,"65,00","975,00",Nao,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10209,Nao,Masculino,0,Nao,Nao,450,Mensal,Boleto bancÃ¡rio,"70,00","31500,00",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10210,Sim,Feminino,0,Sim,Sim,18,Um ano,CartÃ£o de crÃ©dito,"0,01","0,18",Nao,DSL,Nao,Nao,Nordeste,2026-02-13
10,NE-10211,Nao,Masculino,1,Nao,Nao,60,Dois anos,DÃ©bito automÃ¡tico,"50,00","3000,00",Sim,DSL,Sim,Sim,Nordeste,2026-02-13
11,NE-10212,Sim,Feminino,0,Sim,Nao,6,Mensal,Boleto bancÃ¡rio,"890,00","5340,00",Sim,Fibra Ã³tica,Sim,Sim,Nordeste,2026-02-13
12,NE-10213,Nao,Masculino,0,Nao,Sim,30,Dois anos,CartÃ£o de crÃ©dito,"85,00","2550,00",Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
13,NE-10214,Sim,Feminino,1,Sim,Nao,10,Mensal,Boleto bancÃ¡rio,"95,00","950,00",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
14,NE-10215,Nao,Masculino,0,Nao,Nao,42,Dois anos,DÃ©bito automÃ¡tico,"58,00","2436,00",Sim,DSL,Sim,Sim,Nordeste,2026-02-13

In [1284]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 15 non-null     str
 1   churn                      15 non-null     str
 2   info_pessoal_genero        15 non-null     str
 3   info_pessoal_idoso         15 non-null     int64
 4   info_pessoal_parceiro      15 non-null     str
 5   info_pessoal_dependentes   15 non-null     str
 6   conta_meses_contrato       15 non-null     int64
 7   conta_tipo_contrato        15 non-null     str
 8   conta_pagamento            15 non-null     str
 9   conta_cobranca_mensal      15 non-null     str
 10  conta_cobranca_total       15 non-null     str
 11  servicos_telefone          15 non-null     str
 12  servicos_internet          15 non-null     str
 13  servicos_seguranca_online  15 non-null     str
 14  servicos_backup_online     15 non-null     str
 15  regional                   15 non-null     str
 16  data_extracao              15 non-null     str
dtypes: int64(2), str(15)
memory usage: 2.1 KB

In [1285]:
dados_normalizados[['conta_cobranca_mensal', 'conta_cobranca_total']] = dados_normalizados[['conta_cobranca_mensal', 'conta_cobranca_total']].replace(',', '.', regex=True)

In [1286]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 15 non-null     str
 1   churn                      15 non-null     str
 2   info_pessoal_genero        15 non-null     str
 3   info_pessoal_idoso         15 non-null     int64
 4   info_pessoal_parceiro      15 non-null     str
 5   info_pessoal_dependentes   15 non-null     str
 6   conta_meses_contrato       15 non-null     int64
 7   conta_tipo_contrato        15 non-null     str
 8   conta_pagamento            15 non-null     str
 9   conta_cobranca_mensal      15 non-null     str
 10  conta_cobranca_total       15 non-null     str
 11  servicos_telefone          15 non-null     str
 12  servicos_internet          15 non-null     str
 13  servicos_seguranca_online  15 non-null     str
 14  servicos_backup_online     15 non-null     str
 15  regional                   15 non-null     str
 16  data_extracao              15 non-null     str
dtypes: int64(2), str(15)
memory usage: 2.1 KB

In [1287]:
dados_normalizados['conta_cobranca_mensal'] = pd.to_numeric(dados_normalizados['conta_cobranca_mensal'], errors='raise')
dados_normalizados['conta_cobranca_total'] = pd.to_numeric(dados_normalizados['conta_cobranca_total'], errors='raise')

In [1288]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 15 non-null     str
 1   churn                      15 non-null     str
 2   info_pessoal_genero        15 non-null     str
 3   info_pessoal_idoso         15 non-null     int64
 4   info_pessoal_parceiro      15 non-null     str
 5   info_pessoal_dependentes   15 non-null     str
 6   conta_meses_contrato       15 non-null     int64
 7   conta_tipo_contrato        15 non-null     str
 8   conta_pagamento            15 non-null     str
 9   conta_cobranca_mensal      15 non-null     float64
 10  conta_cobranca_total       15 non-null     float64
 11  servicos_telefone          15 non-null     str
 12  servicos_internet          15 non-null     str
 13  servicos_seguranca_online  15 non-null     str
 14  servicos_backup_online     15 non-null     str
 15  regional                   15 non-null     str
 16  data_extracao              15 non-null     str
dtypes: float64(2), int64(2), str(13)
memory usage: 2.1 KB

In [1289]:
dados_normalizados['data_extracao'] = pd.to_datetime(dados_normalizados['data_extracao'], format='%Y-%m-%d')

In [1290]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 15 non-null     str
 1   churn                      15 non-null     str
 2   info_pessoal_genero        15 non-null     str
 3   info_pessoal_idoso         15 non-null     int64
 4   info_pessoal_parceiro      15 non-null     str
 5   info_pessoal_dependentes   15 non-null     str
 6   conta_meses_contrato       15 non-null     int64
 7   conta_tipo_contrato        15 non-null     str
 8   conta_pagamento            15 non-null     str
 9   conta_cobranca_mensal      15 non-null     float64
 10  conta_cobranca_total       15 non-null     float64
 11  servicos_telefone          15 non-null     str
 12  servicos_internet          15 non-null     str
 13  servicos_seguranca_online  15 non-null     str
 14  servicos_backup_online     15 non-null     str
 15  regional                   15 non-null     str
 16  data_extracao              15 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(12)
memory usage: 2.1 KB

In [1291]:
colunas_str = dados_normalizados.select_dtypes('str').columns

In [1292]:
dados_normalizados[colunas_str] = dados_normalizados[colunas_str].apply(lambda x: x.str.strip()).replace('', np.nan)

In [1293]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
2,NE-10203,Sim,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
3,NE-10204,Nao,Feminino,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
5,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
6,NE-10207,Nao,Masculino,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10208,Nao,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10209,Nao,Masculino,0,Nao,Nao,450,Mensal,Boleto bancÃ¡rio,70.00,31500.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10210,Sim,Feminino,0,Sim,Sim,18,Um ano,CartÃ£o de crÃ©dito,0.01,0.18,Nao,DSL,Nao,Nao,Nordeste,2026-02-13
10,NE-10211,Nao,Masculino,1,Nao,Nao,60,Dois anos,DÃ©bito automÃ¡tico,50.00,3000.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
11,NE-10212,Sim,Feminino,0,Sim,Nao,6,Mensal,Boleto bancÃ¡rio,890.00,5340.00,Sim,Fibra Ã³tica,Sim,Sim,Nordeste,2026-02-13
12,NE-10213,Nao,Masculino,0,Nao,Sim,30,Dois anos,CartÃ£o de crÃ©dito,85.00,2550.00,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
13,NE-10214,Sim,Feminino,1,Sim,Nao,10,Mensal,Boleto bancÃ¡rio,95.00,950.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
14,NE-10215,Nao,Masculino,0,Nao,Nao,42,Dois anos,DÃ©bito automÃ¡tico,58.00,2436.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13

In [1294]:
dados_normalizados.isna().sum()

# Por meio desse comando, é possível verificar que, após a transformação dos dados, não existem dados nulos

id_cliente                   0
churn                        0
info_pessoal_genero          0
info_pessoal_idoso           0
info_pessoal_parceiro        0
info_pessoal_dependentes     0
conta_meses_contrato         0
conta_tipo_contrato          0
conta_pagamento              0
conta_cobranca_mensal        0
conta_cobranca_total         0
servicos_telefone            0
servicos_internet            0
servicos_seguranca_online    0
servicos_backup_online       0
regional                     0
data_extracao                0
dtype: int64

In [1295]:
dados_normalizados.duplicated().sum()

# Por meio desse comando, é possível verificar que, após a transformação dos dados, não existem dados duplicados

np.int64(0)

In [1296]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
2,NE-10203,Sim,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
3,NE-10204,Nao,Feminino,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
5,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
6,NE-10207,Nao,Masculino,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10208,Nao,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10209,Nao,Masculino,0,Nao,Nao,450,Mensal,Boleto bancÃ¡rio,70.00,31500.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10210,Sim,Feminino,0,Sim,Sim,18,Um ano,CartÃ£o de crÃ©dito,0.01,0.18,Nao,DSL,Nao,Nao,Nordeste,2026-02-13
10,NE-10211,Nao,Masculino,1,Nao,Nao,60,Dois anos,DÃ©bito automÃ¡tico,50.00,3000.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
11,NE-10212,Sim,Feminino,0,Sim,Nao,6,Mensal,Boleto bancÃ¡rio,890.00,5340.00,Sim,Fibra Ã³tica,Sim,Sim,Nordeste,2026-02-13
12,NE-10213,Nao,Masculino,0,Nao,Sim,30,Dois anos,CartÃ£o de crÃ©dito,85.00,2550.00,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
13,NE-10214,Sim,Feminino,1,Sim,Nao,10,Mensal,Boleto bancÃ¡rio,95.00,950.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
14,NE-10215,Nao,Masculino,0,Nao,Nao,42,Dois anos,DÃ©bito automÃ¡tico,58.00,2436.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13

In [1297]:
def calc_outliers(column, dataframe):
    contagem = 0

    Q1 = dataframe[column].quantile(.25)
    Q3 = dataframe[column].quantile(.75)

    IQR = Q3 - Q1

    limite_inferior = Q1 - (1.5 * IQR)
    limite_superior = Q3 + (1.5 * IQR)

    print(f'Describe inicial: {dataframe[['conta_meses_contrato', 'conta_cobranca_mensal', 'conta_cobranca_total']].describe().to_string()}')

    print(f'Para a coluna ({column}), o valor do limite inferior é: {limite_inferior}')
    print(f'Para a coluna ({column}), o valor do limite superior é: {limite_superior}')

    outliers_index = (dataframe[column] < limite_inferior) | (dataframe[column] > limite_superior)

    print('Abaixo seguem os registros que caíram fora dos limites e os seus respectivos valores:')
    print(dataframe[outliers_index][['id_cliente', column]].to_string())

    if((dataframe[column] < limite_inferior).any()):
        contagem += (dataframe[column] < limite_inferior).sum()
        dataframe.loc[outliers_index, column] = limite_inferior

    if((dataframe[column] > limite_superior).any()):
        contagem += (dataframe[column] > limite_superior).sum()
        dataframe.loc[outliers_index, column] = limite_superior

    # Como o DataFrame tem poucos registros e o foco principal é analisar o 'churn',
    # remover linhas não é o ideal.
    # Na pior das hipóteses, mantemos os valores dentro dos limites, para não 'perturbar' muito
    # uma análise de uma determinada coluna com outliers.

    print(f'Na coluna ({column}), foram encontrados e tratados {contagem} outliers.')

    print(f'Describe final: {dataframe[['conta_meses_contrato', 'conta_cobranca_mensal', 'conta_cobranca_total']].describe().to_string()}')

    return dataframe

In [1298]:
dados_normalizados = calc_outliers('conta_cobranca_mensal', dados_normalizados)

Describe inicial:        conta_meses_contrato  conta_cobranca_mensal  conta_cobranca_total
count             15.000000              15.000000             15.000000
mean              50.800000             127.280000           3668.344667
std              111.844407             213.104874           7820.180503
min                1.000000               0.010000              0.180000
25%                9.000000              56.500000            917.000000
50%               18.000000              75.300000           1807.200000
75%               39.000000              97.495000           2493.000000
max              450.000000             890.000000          31500.000000
Para a coluna (conta_cobranca_mensal), o valor do limite inferior é: -4.992500000000007
Para a coluna (conta_cobranca_mensal), o valor do limite superior é: 158.9875
Abaixo seguem os registros que caíram fora dos limites e os seus respectivos valores:
   id_cliente  conta_cobranca_mensal
11   NE-10212                  890.0
Na coluna (conta_cobranca_mensal), foram encontrados e tratados 1 outliers.
Describe final:        conta_meses_contrato  conta_cobranca_mensal  conta_cobranca_total
count             15.000000              15.000000             15.000000
mean              50.800000              78.545833           3668.344667
std              111.844407              37.253865           7820.180503
min                1.000000               0.010000              0.180000
25%                9.000000              56.500000            917.000000
50%               18.000000              75.300000           1807.200000
75%               39.000000              97.495000           2493.000000
max              450.000000             158.987500          31500.000000

In [1299]:
dados_normalizados = calc_outliers('conta_cobranca_total', dados_normalizados)

Describe inicial:        conta_meses_contrato  conta_cobranca_mensal  conta_cobranca_total
count             15.000000              15.000000             15.000000
mean              50.800000              78.545833           3668.344667
std              111.844407              37.253865           7820.180503
min                1.000000               0.010000              0.180000
25%                9.000000              56.500000            917.000000
50%               18.000000              75.300000           1807.200000
75%               39.000000              97.495000           2493.000000
max              450.000000             158.987500          31500.000000
Para a coluna (conta_cobranca_total), o valor do limite inferior é: -1447.0
Para a coluna (conta_cobranca_total), o valor do limite superior é: 4857.0
Abaixo seguem os registros que caíram fora dos limites e os seus respectivos valores:
   id_cliente  conta_cobranca_total
8    NE-10209               31500.0
11   NE-10212                5340.0
Na coluna (conta_cobranca_total), foram encontrados e tratados 2 outliers.
Describe final:        conta_meses_contrato  conta_cobranca_mensal  conta_cobranca_total
count             15.000000              15.000000             15.000000
mean              50.800000              78.545833           1859.944667
std              111.844407              37.253865           1524.766911
min                1.000000               0.010000              0.180000
25%                9.000000              56.500000            917.000000
50%               18.000000              75.300000           1807.200000
75%               39.000000              97.495000           2493.000000
max              450.000000             158.987500           4857.000000

In [1300]:
dados_normalizados = calc_outliers('conta_meses_contrato', dados_normalizados)

Describe inicial:        conta_meses_contrato  conta_cobranca_mensal  conta_cobranca_total
count             15.000000              15.000000             15.000000
mean              50.800000              78.545833           1859.944667
std              111.844407              37.253865           1524.766911
min                1.000000               0.010000              0.180000
25%                9.000000              56.500000            917.000000
50%               18.000000              75.300000           1807.200000
75%               39.000000              97.495000           2493.000000
max              450.000000             158.987500           4857.000000
Para a coluna (conta_meses_contrato), o valor do limite inferior é: -36.0
Para a coluna (conta_meses_contrato), o valor do limite superior é: 84.0
Abaixo seguem os registros que caíram fora dos limites e os seus respectivos valores:
  id_cliente  conta_meses_contrato
8   NE-10209                   450
Na coluna (conta_meses_contrato), foram encontrados e tratados 1 outliers.
Describe final:        conta_meses_contrato  conta_cobranca_mensal  conta_cobranca_total
count             15.000000              15.000000             15.000000
mean              26.400000              78.545833           1859.944667
std               23.814161              37.253865           1524.766911
min                1.000000               0.010000              0.180000
25%                9.000000              56.500000            917.000000
50%               18.000000              75.300000           1807.200000
75%               39.000000              97.495000           2493.000000
max               84.000000             158.987500           4857.000000

In [1302]:
dados_normalizados.to_csv('churn_nordeste_outliers_treated.csv', sep=';', encoding='utf-8', index=False)