In [229]:
import pandas as pd
import numpy as np
import json

In [230]:
with open('churn_nordeste_raw.json', 'r') as f:
    json_bruto = json.load(f)

In [231]:
json_bruto

{'regional': 'Nordeste',
 'data_extracao': '2026-02-13',
 'clientes': [{'id_cliente': 'NE-10201',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 12,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '89,90',
    'cobranca_total': '1078,80'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10201',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 12,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '89,90',
    'cobranca_total': '1078,80'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10202',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 48,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '45,50',
    'cobranca_total': '2184,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10202',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 6,
    'tipo_contrato': 'Mensal',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '72,00',
    'cobranca_total': '432,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10203',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 2,
    'tipo_contrato': 'Mensal',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '120,00',
    'cobranca_total': '240,00'},
   'servicos': {'telefone': 'Nao',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Sim',
    'backup_online': 'Nao'},
   'churn': ' '},
  {'id_cliente': 'NE-10204',
   'info_pessoal': {'genero': '',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 24,
    'tipo_contrato': 'Um ano',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '75,30',
    'cobranca_total': '1807,20'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10205',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 1,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '99,99',
    'cobranca_total': '99,99'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10206',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 36,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '55,00',
    'cobranca_total': '1980,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10207',
   'info_pessoal': {'genero': '',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 8,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '110,50',
    'cobranca_total': '884,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10208',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 15,
    'tipo_contrato': 'Um ano',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '65,00',
    'cobranca_total': '975,00'},
   'servicos': {'telefone': 'Nao',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': ''}]}

In [232]:
dados_normalizados = pd.json_normalize(json_bruto, record_path='clientes', meta=['regional', 'data_extracao'], sep='_')

In [233]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,"89,90","1078,80",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,"89,90","1078,80",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
2,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,"45,50","2184,00",Sim,DSL,Sim,Sim,Nordeste,2026-02-13
3,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,"72,00","432,00",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
4,NE-10203,,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,"120,00","240,00",Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
5,NE-10204,Nao,,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,"75,30","1807,20",Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
6,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,"99,99","99,99",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,"55,00","1980,00",Sim,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10207,Nao,,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,"110,50","884,00",Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10208,,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,"65,00","975,00",Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [234]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 10 non-null     str
 1   churn                      10 non-null     str
 2   info_pessoal_genero        10 non-null     str
 3   info_pessoal_idoso         10 non-null     int64
 4   info_pessoal_parceiro      10 non-null     str
 5   info_pessoal_dependentes   10 non-null     str
 6   conta_meses_contrato       10 non-null     int64
 7   conta_tipo_contrato        10 non-null     str
 8   conta_pagamento            10 non-null     str
 9   conta_cobranca_mensal      10 non-null     str
 10  conta_cobranca_total       10 non-null     str
 11  servicos_telefone          10 non-null     str
 12  servicos_internet          10 non-null     str
 13  servicos_seguranca_online  10 non-null     str
 14  servicos_backup_online     10 non-null     str
 15  regional                   10 non-null     str
 16  data_extracao              10 non-null     str
dtypes: int64(2), str(15)
memory usage: 1.5 KB

In [235]:
dados_normalizados[['conta_cobranca_mensal', 'conta_cobranca_total']] = dados_normalizados[['conta_cobranca_mensal', 'conta_cobranca_total']].replace(',', '.', regex=True)

In [236]:
dados_normalizados['conta_cobranca_mensal'] = pd.to_numeric(dados_normalizados['conta_cobranca_mensal'])
dados_normalizados['conta_cobranca_total'] = pd.to_numeric(dados_normalizados['conta_cobranca_total'])

In [237]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
2,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
3,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
4,NE-10203,,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
5,NE-10204,Nao,,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
6,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10207,Nao,,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10208,,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [238]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 10 non-null     str
 1   churn                      10 non-null     str
 2   info_pessoal_genero        10 non-null     str
 3   info_pessoal_idoso         10 non-null     int64
 4   info_pessoal_parceiro      10 non-null     str
 5   info_pessoal_dependentes   10 non-null     str
 6   conta_meses_contrato       10 non-null     int64
 7   conta_tipo_contrato        10 non-null     str
 8   conta_pagamento            10 non-null     str
 9   conta_cobranca_mensal      10 non-null     float64
 10  conta_cobranca_total       10 non-null     float64
 11  servicos_telefone          10 non-null     str
 12  servicos_internet          10 non-null     str
 13  servicos_seguranca_online  10 non-null     str
 14  servicos_backup_online     10 non-null     str
 15  regional                   10 non-null     str
 16  data_extracao              10 non-null     str
dtypes: float64(2), int64(2), str(13)
memory usage: 1.5 KB

In [239]:
dados_normalizados['data_extracao'] = pd.to_datetime(dados_normalizados['data_extracao'], format='%Y-%m-%d')

In [240]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
2,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
3,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
4,NE-10203,,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
5,NE-10204,Nao,,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
6,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10207,Nao,,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10208,,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [241]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 10 non-null     str
 1   churn                      10 non-null     str
 2   info_pessoal_genero        10 non-null     str
 3   info_pessoal_idoso         10 non-null     int64
 4   info_pessoal_parceiro      10 non-null     str
 5   info_pessoal_dependentes   10 non-null     str
 6   conta_meses_contrato       10 non-null     int64
 7   conta_tipo_contrato        10 non-null     str
 8   conta_pagamento            10 non-null     str
 9   conta_cobranca_mensal      10 non-null     float64
 10  conta_cobranca_total       10 non-null     float64
 11  servicos_telefone          10 non-null     str
 12  servicos_internet          10 non-null     str
 13  servicos_seguranca_online  10 non-null     str
 14  servicos_backup_online     10 non-null     str
 15  regional                   10 non-null     str
 16  data_extracao              10 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(2), str(12)
memory usage: 1.5 KB

In [242]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
2,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
3,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
4,NE-10203,,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
5,NE-10204,Nao,,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
6,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10207,Nao,,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10208,,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [243]:
colunas_strings = dados_normalizados.select_dtypes('str').columns

In [244]:
dados_normalizados[colunas_strings] = dados_normalizados[colunas_strings].apply(lambda x: x.str.strip())

In [245]:
dados_normalizados[colunas_strings] = dados_normalizados[colunas_strings].replace('', np.nan)

In [246]:
dados_normalizados

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
2,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
3,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
4,NE-10203,NaN,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
5,NE-10204,Nao,NaN,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
6,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
7,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
8,NE-10207,Nao,NaN,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
9,NE-10208,NaN,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [247]:
dados_normalizados.isna().sum()

id_cliente                   0
churn                        2
info_pessoal_genero          2
info_pessoal_idoso           0
info_pessoal_parceiro        0
info_pessoal_dependentes     0
conta_meses_contrato         0
conta_tipo_contrato          0
conta_pagamento              0
conta_cobranca_mensal        0
conta_cobranca_total         0
servicos_telefone            0
servicos_internet            0
servicos_seguranca_online    0
servicos_backup_online       0
regional                     0
data_extracao                0
dtype: int64

In [248]:
dados_normalizados.shape[0]

10

In [249]:
dados_sem_duplicadas = dados_normalizados.drop_duplicates()

# Como o método .drop_duplicate(), por default, compara todas as colunas do DataFrame, ele identifica linhas que tem o mesmo id_cliente,
# mas com outras células com valores diferentes. Dessa forma, essas linhas são consideradas como diferentes.

In [250]:
dados_sem_duplicadas.reset_index(drop=True, inplace=True)

In [251]:
linhas_removidas = dados_normalizados.shape[0] - dados_sem_duplicadas.shape[0]

In [252]:
print(f'A quantidade de linhas duplicadas reais removidas é: {linhas_removidas}')

A quantidade de linhas duplicadas reais removidas é: 1

In [253]:
dados_sem_duplicadas

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
2,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
3,NE-10203,NaN,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
4,NE-10204,Nao,NaN,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
5,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
6,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
7,NE-10207,Nao,NaN,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
8,NE-10208,NaN,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [254]:
moda = dados_sem_duplicadas['info_pessoal_genero'].mode()

In [255]:
moda[0]

'Feminino'

In [256]:
colunas_valores_nulos = dados_sem_duplicadas.isna().sum()

In [257]:
dados_sem_duplicadas['info_pessoal_genero'] = dados_sem_duplicadas['info_pessoal_genero'].fillna(moda[0])

In [258]:
dados_sem_duplicadas

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
2,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
3,NE-10203,NaN,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao,Nordeste,2026-02-13
4,NE-10204,Nao,Feminino,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
5,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
6,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
7,NE-10207,Nao,Feminino,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
8,NE-10208,NaN,Feminino,1,Nao,Nao,15,Um ano,DÃ©bito automÃ¡tico,65.00,975.00,Nao,DSL,Sim,Sim,Nordeste,2026-02-13

In [259]:
dados_sem_duplicadas.dropna(subset='churn', inplace=True)

# Como o objetivo principal da análise dos dados é verificar se houve ou não 'churn', as linhas em que os valores da célula dessa coluna sejam NaN
# não ajudaram em nada na referida análise. Motivo este dessas linhas poderem ser removidas do DataFrame sem nenhum prejuízo aparente.

In [260]:
dados_sem_duplicadas.reset_index(drop=True, inplace=True)

In [261]:
dados_sem_duplicadas

,id_cliente,churn,info_pessoal_genero,info_pessoal_idoso,info_pessoal_parceiro,info_pessoal_dependentes,conta_meses_contrato,conta_tipo_contrato,conta_pagamento,conta_cobranca_mensal,conta_cobranca_total,servicos_telefone,servicos_internet,servicos_seguranca_online,servicos_backup_online,regional,data_extracao
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
2,NE-10202,Sim,Feminino,1,Nao,Nao,6,Mensal,DÃ©bito automÃ¡tico,72.00,432.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
3,NE-10204,Nao,Feminino,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim,Nordeste,2026-02-13
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13
5,NE-10206,Nao,Masculino,0,Nao,Nao,36,Dois anos,CartÃ£o de crÃ©dito,55.00,1980.00,Sim,DSL,Sim,Sim,Nordeste,2026-02-13
6,NE-10207,Nao,Feminino,0,Sim,Sim,8,Mensal,Boleto bancÃ¡rio,110.50,884.00,Sim,Fibra Ã³tica,Nao,Nao,Nordeste,2026-02-13

In [262]:
print(f"""
RELATÓRIO FINAL
===============
- A quantidade de duplicatas reais removidas é: {linhas_removidas};
- A quantidade de nulos preenchidos pela moda da coluna 'info_pessoal_genero' é: {colunas_valores_nulos['info_pessoal_genero']};
- A quantidade de linhas dropadas por nulo no target é: {colunas_valores_nulos['churn']};
- O DataFrame final ficou com o seguinte shape:
    - Linhas: {dados_sem_duplicadas.shape[0]};
    - Colunas: {dados_sem_duplicadas.shape[1]}.
""")

RELATÓRIO FINAL
===============
- A quantidade de duplicatas reais removidas é: 1;
- A quantidade de nulos preenchidos pela moda da coluna 'info_pessoal_genero' é: 2;
- A quantidade de linhas dropadas por nulo no target é: 2;
- O DataFrame final ficou com o seguinte shape:
    - Linhas: 7;
    - Colunas: 17.

In [263]:
dados_sem_duplicadas.to_csv('churn_nordeste_clean.csv', sep=';', encoding='utf-8')