In [220]:
import pandas as pd
import numpy as np
import json

In [221]:
with open('churn_nordeste_raw.json', 'r') as file:
    json_bruto = json.load(file)

In [222]:
json_bruto

{'regional': 'Nordeste',
 'data_extracao': '2026-02-13',
 'clientes': [{'id_cliente': 'NE-10201',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 12,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '89,90',
    'cobranca_total': '1078,80'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'},
  {'id_cliente': 'NE-10202',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 48,
    'tipo_contrato': 'Dois anos',
    'pagamento': 'CartÃ£o de crÃ©dito',
    'cobranca_mensal': '45,50',
    'cobranca_total': '2184,00'},
   'servicos': {'telefone': 'Sim',
    'internet': 'DSL',
    'seguranca_online': 'Sim',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10203',
   'info_pessoal': {'genero': 'Masculino',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Sim'},
   'conta': {'meses_contrato': 2,
    'tipo_contrato': 'Mensal',
    'pagamento': 'DÃ©bito automÃ¡tico',
    'cobranca_mensal': '120,00',
    'cobranca_total': '240,00'},
   'servicos': {'telefone': 'Nao',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Sim',
    'backup_online': 'Nao'},
   'churn': ' '},
  {'id_cliente': 'NE-10204',
   'info_pessoal': {'genero': '',
    'idoso': 0,
    'parceiro': 'Sim',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 24,
    'tipo_contrato': 'Um ano',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '75,30',
    'cobranca_total': '1807,20'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Sim'},
   'churn': 'Nao'},
  {'id_cliente': 'NE-10205',
   'info_pessoal': {'genero': 'Feminino',
    'idoso': 1,
    'parceiro': 'Nao',
    'dependentes': 'Nao'},
   'conta': {'meses_contrato': 1,
    'tipo_contrato': 'Mensal',
    'pagamento': 'Boleto bancÃ¡rio',
    'cobranca_mensal': '99,99',
    'cobranca_total': '99,99'},
   'servicos': {'telefone': 'Sim',
    'internet': 'Fibra Ã³tica',
    'seguranca_online': 'Nao',
    'backup_online': 'Nao'},
   'churn': 'Sim'}]}

In [223]:
dados_normalizados = pd.json_normalize(json_bruto, record_path=['clientes'])

In [224]:
dados_normalizados

,id_cliente,churn,info_pessoal.genero,info_pessoal.idoso,info_pessoal.parceiro,info_pessoal.dependentes,conta.meses_contrato,conta.tipo_contrato,conta.pagamento,conta.cobranca_mensal,conta.cobranca_total,servicos.telefone,servicos.internet,servicos.seguranca_online,servicos.backup_online
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,"89,90","1078,80",Sim,Fibra Ã³tica,Nao,Nao
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,"45,50","2184,00",Sim,DSL,Sim,Sim
2,NE-10203,,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,"120,00","240,00",Nao,Fibra Ã³tica,Sim,Nao
3,NE-10204,Nao,,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,"75,30","1807,20",Sim,Fibra Ã³tica,Nao,Sim
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,"99,99","99,99",Sim,Fibra Ã³tica,Nao,Nao

In [225]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 5 non-null      str
 1   churn                      5 non-null      str
 2   info_pessoal.genero        5 non-null      str
 3   info_pessoal.idoso         5 non-null      int64
 4   info_pessoal.parceiro      5 non-null      str
 5   info_pessoal.dependentes   5 non-null      str
 6   conta.meses_contrato       5 non-null      int64
 7   conta.tipo_contrato        5 non-null      str
 8   conta.pagamento            5 non-null      str
 9   conta.cobranca_mensal      5 non-null      str
 10  conta.cobranca_total       5 non-null      str
 11  servicos.telefone          5 non-null      str
 12  servicos.internet          5 non-null      str
 13  servicos.seguranca_online  5 non-null      str
 14  servicos.backup_online     5 non-null      str
dtypes: int64(2), str(13)
memory usage: 732.0 bytes

In [226]:
dados_normalizados[dados_normalizados.select_dtypes('str').columns] = dados_normalizados.select_dtypes('str').apply(lambda x: x.str.strip())

In [244]:
contagem = (dados_normalizados == '').sum()

In [248]:
total_vazios = contagem[contagem > 0].sum()

In [267]:
colunas = contagem[contagem > 0]

In [271]:
print(f'{total_vazios} células foram convertidas de string vazia/espaço nas colunas: ')
for x,y in colunas.items():
    print(x)

2 células foram convertidas de string vazia/espaço nas colunas:
churn
info_pessoal.genero

In [270]:
dados_normalizados[dados_normalizados.select_dtypes('str').columns] = dados_normalizados.select_dtypes('str').apply(lambda x: x.replace('', np.nan))

In [190]:
dados_normalizados

,id_cliente,churn,info_pessoal.genero,info_pessoal.idoso,info_pessoal.parceiro,info_pessoal.dependentes,conta.meses_contrato,conta.tipo_contrato,conta.pagamento,conta.cobranca_mensal,conta.cobranca_total,servicos.telefone,servicos.internet,servicos.seguranca_online,servicos.backup_online
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,"89,90","1078,80",Sim,Fibra Ã³tica,Nao,Nao
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,"45,50","2184,00",Sim,DSL,Sim,Sim
2,NE-10203,NaN,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,"120,00","240,00",Nao,Fibra Ã³tica,Sim,Nao
3,NE-10204,Nao,NaN,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,"75,30","1807,20",Sim,Fibra Ã³tica,Nao,Sim
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,"99,99","99,99",Sim,Fibra Ã³tica,Nao,Nao

In [191]:
dados_normalizados

,id_cliente,churn,info_pessoal.genero,info_pessoal.idoso,info_pessoal.parceiro,info_pessoal.dependentes,conta.meses_contrato,conta.tipo_contrato,conta.pagamento,conta.cobranca_mensal,conta.cobranca_total,servicos.telefone,servicos.internet,servicos.seguranca_online,servicos.backup_online
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,"89,90","1078,80",Sim,Fibra Ã³tica,Nao,Nao
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,"45,50","2184,00",Sim,DSL,Sim,Sim
2,NE-10203,NaN,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,"120,00","240,00",Nao,Fibra Ã³tica,Sim,Nao
3,NE-10204,Nao,NaN,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,"75,30","1807,20",Sim,Fibra Ã³tica,Nao,Sim
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,"99,99","99,99",Sim,Fibra Ã³tica,Nao,Nao

In [192]:
dados_normalizados['conta.cobranca_mensal'] = dados_normalizados['conta.cobranca_mensal'].apply(lambda x: x.replace(',', '.'))

In [193]:
dados_normalizados['conta.cobranca_total'] = dados_normalizados['conta.cobranca_total'].apply(lambda x: x.replace(',', '.'))

In [194]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 5 non-null      str
 1   churn                      4 non-null      str
 2   info_pessoal.genero        4 non-null      str
 3   info_pessoal.idoso         5 non-null      int64
 4   info_pessoal.parceiro      5 non-null      str
 5   info_pessoal.dependentes   5 non-null      str
 6   conta.meses_contrato       5 non-null      int64
 7   conta.tipo_contrato        5 non-null      str
 8   conta.pagamento            5 non-null      str
 9   conta.cobranca_mensal      5 non-null      str
 10  conta.cobranca_total       5 non-null      str
 11  servicos.telefone          5 non-null      str
 12  servicos.internet          5 non-null      str
 13  servicos.seguranca_online  5 non-null      str
 14  servicos.backup_online     5 non-null      str
dtypes: int64(2), str(13)
memory usage: 732.0 bytes

In [195]:
dados_normalizados['conta.cobranca_mensal'] = pd.to_numeric(dados_normalizados['conta.cobranca_mensal'], errors='coerce')

In [196]:
dados_normalizados['conta.cobranca_total'] = pd.to_numeric(dados_normalizados['conta.cobranca_total'], errors='coerce')

In [197]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 5 non-null      str
 1   churn                      4 non-null      str
 2   info_pessoal.genero        4 non-null      str
 3   info_pessoal.idoso         5 non-null      int64
 4   info_pessoal.parceiro      5 non-null      str
 5   info_pessoal.dependentes   5 non-null      str
 6   conta.meses_contrato       5 non-null      int64
 7   conta.tipo_contrato        5 non-null      str
 8   conta.pagamento            5 non-null      str
 9   conta.cobranca_mensal      5 non-null      float64
 10  conta.cobranca_total       5 non-null      float64
 11  servicos.telefone          5 non-null      str
 12  servicos.internet          5 non-null      str
 13  servicos.seguranca_online  5 non-null      str
 14  servicos.backup_online     5 non-null      str
dtypes: float64(2), int64(2), str(11)
memory usage: 732.0 bytes

In [198]:
dados_normalizados

,id_cliente,churn,info_pessoal.genero,info_pessoal.idoso,info_pessoal.parceiro,info_pessoal.dependentes,conta.meses_contrato,conta.tipo_contrato,conta.pagamento,conta.cobranca_mensal,conta.cobranca_total,servicos.telefone,servicos.internet,servicos.seguranca_online,servicos.backup_online
0,NE-10201,Sim,Masculino,0,Sim,Nao,12,Mensal,Boleto bancÃ¡rio,89.90,1078.80,Sim,Fibra Ã³tica,Nao,Nao
1,NE-10202,Nao,Feminino,1,Nao,Nao,48,Dois anos,CartÃ£o de crÃ©dito,45.50,2184.00,Sim,DSL,Sim,Sim
2,NE-10203,NaN,Masculino,0,Sim,Sim,2,Mensal,DÃ©bito automÃ¡tico,120.00,240.00,Nao,Fibra Ã³tica,Sim,Nao
3,NE-10204,Nao,NaN,0,Sim,Nao,24,Um ano,Boleto bancÃ¡rio,75.30,1807.20,Sim,Fibra Ã³tica,Nao,Sim
4,NE-10205,Sim,Feminino,1,Nao,Nao,1,Mensal,Boleto bancÃ¡rio,99.99,99.99,Sim,Fibra Ã³tica,Nao,Nao

In [199]:
dados_normalizados['conta.meses_contrato'].info()

<class 'pandas.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: conta.meses_contrato
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 172.0 bytes

In [200]:
dados_normalizados.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_cliente                 5 non-null      str
 1   churn                      4 non-null      str
 2   info_pessoal.genero        4 non-null      str
 3   info_pessoal.idoso         5 non-null      int64
 4   info_pessoal.parceiro      5 non-null      str
 5   info_pessoal.dependentes   5 non-null      str
 6   conta.meses_contrato       5 non-null      int64
 7   conta.tipo_contrato        5 non-null      str
 8   conta.pagamento            5 non-null      str
 9   conta.cobranca_mensal      5 non-null      float64
 10  conta.cobranca_total       5 non-null      float64
 11  servicos.telefone          5 non-null      str
 12  servicos.internet          5 non-null      str
 13  servicos.seguranca_online  5 non-null      str
 14  servicos.backup_online     5 non-null      str
dtypes: float64(2), int64(2), str(11)
memory usage: 732.0 bytes

In [272]:
dados_normalizados.to_csv('churn_nordeste_transformed.csv', sep=';', index=False, encoding='utf-8')